-- Crear tabla Líneas
-- Ejecuta este script en el SQL Editor de Supabase

-- Tabla de líneas (nivel superior en la jerarquía)
CREATE TABLE public.lineas (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  descripcion text not null,
  
  constraint lineas_pkey primary key (id),
  constraint lineas_descripcion_unique unique (descripcion)
);

-- Crear índice para búsquedas por descripción
CREATE INDEX lineas_descripcion_idx ON public.lineas (descripcion);

-- Habilitar Row Level Security (RLS)
ALTER TABLE public.lineas ENABLE ROW LEVEL SECURITY;

-- Crear políticas de seguridad
CREATE POLICY "Permitir acceso completo a lineas" on public.lineas
  for all using (true);

-- Agregar comentario para documentación
COMMENT ON TABLE public.lineas IS 'Tabla de líneas de productos (nivel superior en la jerarquía Línea > Categoría > Producto)';
COMMENT ON COLUMN public.lineas.id IS 'Identificador único de la línea';
COMMENT ON COLUMN public.lineas.descripcion IS 'Nombre/descripción de la línea';
COMMENT ON COLUMN public.lineas.created_at IS 'Fecha de creación de la línea';

-- Insertar algunas líneas de ejemplo (opcional)
INSERT INTO public.lineas (descripcion) VALUES 
('Electrónicos'),
('Hogar y Jardín'),
('Deportes y Fitness'),
('Moda y Accesorios'),
('Automotor');